### ISSUE TITLE
hold header in bottom of UINavigationBar [ iOS 10 ]

### ISSUE THREAD

**Issue by ahmedraad** [romansorochak/ParallaxHeader#23]
Hi, Thanks for this amazing library
i've noticed there's an issue with iOS 10 when scroll to top and when navigation bar is Translucent

You can see the different bellow

iOS 11 - Working correctly 
![screen shot 2018-02-13 at 10 59 49 am](https://user-images.githubusercontent.com/17860965/36139265-e6de0362-10ad-11e8-95f9-3ee1f871c6d6.png)
iOS 10 - has an issue
![screen shot 2018-02-13 at 11 00 36 am](https://user-images.githubusercontent.com/17860965/36139315-1514bd48-10ae-11e8-9502-36c089c3f980.png)

**Comment by ahmedraad** [comment]
@romansorochak can you please check it - i really needed this

**Comment by furiosFast** [comment]
have you find the solution?
