### ISSUE TITLE
iOS 10 Status bar issue

### ISSUE THREAD

**Issue by fabiangiger** [romansorochak/ParallaxHeader#26]
Hi All,

I'm having having an issue where the header is shown bellow the status bar. 
So the header.y == statubar.maxY. 
The tableview's.y == 0. So the content is shown bellow the status bar.
Can anyone help?

Thanks in advance!

**Comment by jhrasco** [comment]
```
let statusBarHeight = UIApplication.shared.statusBarFrame.height
tableView.contentInset = UIEdgeInsetsMake(-statusBarHeight, 0.0, 0.0, 0.0)
```
