### ISSUE TITLE
Swift 4 

### ISSUE THREAD

**Issue by Huddie** [romansorochak/ParallaxHeader#3]
The header view label is pushed up too high. Could be a problem with snapKit. They have a swift 4 branch i tried installing by this repo installs 3.2

**Comment by XOneto9** [comment]
I have same issue.
but the snapKit v3.2 appear same problem.

the parallax view is much high.

**Comment by XOneto9** [comment]
Self, solution.

In my case, the scroll top constraint is changed like as edge of top screen not navigation bottom.
